### ISSUE TITLE
Missing Widgets

### ISSUE THREAD

**Issue by suffisme** [nairraghav/aim-practice#1]
Came across this pygame repository of yours.
Only arrow board is visible, I think you should add some arrow effect upon clicking.
![pygame](https://user-images.githubusercontent.com/28235081/83364511-59450d00-a3bf-11ea-8fe4-ba7d4041c814.png)

**Comment by nairraghav** [comment]
I’m not sure I understand the request here, could you phrase it in another way?

**Comment by suffisme** [comment]
I meant to say, you should have an arrow or hitting effect on clicking upon the arrow board.
Moreover, A readme would be preferred explaining working, controls and rules of the games.
And by missing widgets, I pre assumed you wanted to create arrows, floating and hitting on the board.

**Comment by nairraghav** [comment]
Ah, that makes sense. I will add some sort of feedback on clicking the targets and add more info in the readme. Appreciate the feedback, thanks!

**Comment by suffisme** [comment]
Your welcome.
